const descriptions = [
    "Une silhouette imposante avec un regard perçant.", "Toujours souriant, mais cache une grande tristesse.", "Connue pour sa grande sagesse et sa patience.",
    "Rapide comme l'éclair, personne ne l'a jamais battu en duel.", "Maître des éléments, il peut contrôler le feu et l'eau à volonté.",
    "Un charmeur né, capable de convaincre même les plus sceptiques.", "Porte une cicatrice qui raconte une histoire de survie.", "A une connexion spéciale avec les animaux.",
    "Cherche la rédemption pour un passé trouble.", "Courageux et loyal, prêt à tout pour protéger ses amis.", "Son sourire est aussi dangereux que ses lames.",
    "Son rire résonne comme un écho dans les montagnes.", "Personne ne connaît son véritable nom ni son visage.", "Voyageur solitaire, il a vu plus de pays que quiconque.",
    "Ses yeux brillent d'une lueur mystérieuse.", "A grandi dans une forêt enchantée, entouré de créatures magiques.", "A la capacité de parler aux esprits.",
    "Toujours prêt à aider les plus faibles et les opprimés.", "A une force surhumaine, même pour sa race.", "Connu pour sa grande générosité et son altruisme.",
    "Maîtrise l'art de la guérison comme personne.", "A une rancune éternelle contre les forces du mal.", "Peut invoquer des créatures mystiques à volonté.",
    "Sa voix est douce et mélodieuse, capable de calmer les tempêtes.", "Porte une épée légendaire transmise de génération en génération.",
    "A une affinité naturelle avec les plantes et les animaux.", "Peut voir l'avenir dans les étoiles.", "Est un maître du déguisement et de l'infiltration.",
    "A une cicatrice en forme d'éclair sur le bras.", "Peut contrôler les ombres et se déplacer à travers elles.", "A un tatouage magique qui brille dans l'obscurité.",
    "Sa simple présence inspire la peur chez ses ennemis.", "A été banni de son royaume pour un crime qu'il n'a pas commis.", "Peut se transformer en animal à volonté.",
    "A fait un pacte avec un ancien esprit pour obtenir ses pouvoirs.", "Porte toujours un médaillon mystérieux autour du cou.", "Peut manipuler le temps pour ralentir ou accélérer les événements.",
    "Est connu pour ses talents de conteur et ses histoires captivantes.", "A une cicatrice de brûlure sur le côté du visage.", "Peut communiquer avec les morts.",
    "Est à la recherche d'un artefact légendaire depuis des années.", "A survécu à une bataille où tout son régiment a été anéanti.", "Est en quête de vengeance pour la mort de sa famille.",
    "A des yeux de différentes couleurs, l'un bleu et l'autre vert.", "A été élevé par des loups dans une forêt sauvage.", "Peut invoquer des tempêtes et des éclairs à volonté.",
    "Est un maître de l'alchimie et peut créer des potions puissantes.", "A un sourire charmeur qui peut faire fondre n'importe quel cœur.", "Peut entendre les pensées des autres.",
    "A des ailes cachées qu'il peut déployer à volonté.", "A juré de protéger les innocents et de combattre l'injustice.", "Porte un masque mystérieux qui cache son visage.",
    "Est un maître du combat à mains nues.", "A une affinité particulière avec les créatures marines.", "Peut créer des illusions réalistes pour tromper ses ennemis.",
    "A des tatouages runiques sur tout le corps.", "Peut lire les pensées en touchant les objets.", "A été béni par un ancien dieu avec des pouvoirs surhumains.",
    "A des cheveux d'une couleur inhabituelle, comme l'argent ou le violet.", "Est toujours accompagné d'un animal fidèle.", "A une aura mystérieuse qui intrigue et effraie à la fois.",
    "A vécu des siècles en utilisant des sorts de longévité.", "A une connaissance encyclopédique des plantes et de leurs usages.", "Peut se rendre invisible à volonté.",
    "A un rire contagieux qui peut remonter le moral de n'importe qui.", "Est capable de survivre dans les conditions les plus extrêmes.", "A des yeux perçants capables de voir à travers les mensonges.",
    "Porte un anneau magique qui lui confère des pouvoirs spéciaux.", "Peut manipuler les éléments à volonté.", "A une grande cicatrice traversant son torse.",
    "Est doté d'une force et d'une agilité extraordinaires.", "A une connaissance approfondie de la magie noire.", "Peut contrôler les animaux avec un simple regard.",
    "Est connu pour ses talents de forgeron et peut créer des armes légendaires.", "Peut se fondre dans les ombres et devenir invisible.", "A une mémoire photographique et se souvient de tout ce qu'il voit.",
    "Peut invoquer des esprits pour obtenir des conseils.", "A un regard glacial qui peut figer de peur ses ennemis.", "Est doté d'une intelligence exceptionnelle et est un stratège hors pair."
];
